cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'pivotal/tap'
tap 'cloudfoundry/tap'
tap 'caskroom/versions'
tap 'universal-ctags/universal-ctags'
tap 'git-duet/tap'

brew 'ack'
brew 'autojump'
brew 'cf-cli'
brew 'coreutils'
# brew 'docker'
# brew 'docker-compose'
# brew 'docker-machine'
brew 'exercism'
brew 'git'
brew 'git-duet'
brew 'git-pair'
brew 'gnupg'
brew 'gnupg2'
brew 'go', args: ['--cross-compile-common']
brew 'gradle'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libgit2'
brew 'neovim'
brew 'node'
brew 'openssl'
brew 'python'
brew 'python3'
brew 'reattach-to-user-namespace'
brew 'ruby-build'
brew 'readline'
brew 'rbenv'
brew 'sbt'
brew 'scala'
brew 'ssh-copy-id'
brew 'universal-ctags', args: ['HEAD']
brew 'vim', args: ['with-lua', 'with-override-system-vi', 'with-python3', 'HEAD']
brew 'wget'
brew 'yarn'
brew 'zsh'

cask 'alfred'
cask 'airserver'
cask 'bartender'
cask 'dropbox'
cask 'evernote'
cask 'flux'
cask 'google-chrome'
cask 'intellij-idea'
cask 'iterm2-beta'
cask 'java'
cask 'kindle'
cask 'postman'
cask 'pycharm'
cask 'slack'
cask 'vagrant'
cask 'visual-studio-code'
cask 'virtualbox'
cask 'webstorm'
