#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

echo "-----------------------"
echo "> updating linux"
sudo apt update || true 
sudo apt upgrade -y || true
cat packages.txt | xargs sudo apt-get install -y
sudo apt autoremove -y
sudo apt clean
echo "-----------------------"

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
