#!/usr/bin/env bash
#
# Run all dotfiles installers.

cd "$(dirname $0)"/..

if test ! $(which brew)
then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

echo "-----------------------"
echo "> updating with homebrew"
brew update
brew upgrade
brew cleanup
brew bundle dump --all --force --file=./tmp/Brewfile
echo "-----------------------"

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
