alias reload!='. ~/.zshrc'
alias vi='nvim'
alias ls='ls --color=auto'
alias myip='curl ifconfig.me'
alias fixtime='sudo hwclock --hctosys'
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xlip -selection clipboard -o'
